### ISSUE TITLE
En el update se perdió la automatización de cargar el label de `cfp`

### ISSUE THREAD

**Issue by paulotijero** [opentech-pe/opentech.pe#137]
En el update se perdieron la automatizacion de cargar el label de `cfp`

_Originally posted by @paulotijero in https://github.com/opentech-pe/opentech.pe/pull/136#pullrequestreview-1241162794_

Ref: #135

**Comment by JimmyLoloy98** [comment]
No entiendo, es un argumento en la URL, sigue redirigiendo correctamente, ya que es tema de la configuración desde github.  🤔
