### ISSUE TITLE
3 razones por las cuales usar gitflow

### ISSUE THREAD

**Issue by tonystart** [opentech-pe/opentech.pe#25]
## ¿Qué tipo de presentación quieres hacer?
- [x] Keynote (20 a 30 minutos)

## ¿Cuál es tu nombre?
Tony Manuel Ojeda Vela

## Cuéntanos un poco sobre ti
Un chico simpatico e inteligente que le encantan las tecnologías de desarrollo web

## ¿Cuál es el título de tu charla?
3 razones por las cuales usar gitflow

## Danos una descripción de tu charla (20 palabras)
Gitflow un flujo de trabajo en git aportando a llevar una mejor organización y control en el desarrollo de nuestros proyectos.

## ¿Tienes alguna red social donde podamos contactarte?
[Github](https://github.com/tony-ojeda), [Twitter](https://twitter.com/tony_ojedaV)

**Comment by jhonfitzgerald** [comment]
Aprovado para este segundo Feves 14/Nov/2019 ^_^
