### ISSUE TITLE
Introducción a angular y no morir en el intento.

### ISSUE THREAD

**Issue by thelinch** [opentech-pe/opentech.pe#26]
## ¿Qué tipo de presentación quieres hacer?
- [x] Keynote (20 a 30 minutos)
## ¿Cuál es tu nombre?
Antony Inga Atunga
## Cuéntanos un poco sobre ti
Amante de la tecnología y su uso adecuado.
## ¿Cuál es el título de tu charla?
Introducción a angular y no morir en el intento.
## Danos una descripción de tu charla (20 palabras)
Hablaremos sobre que es un componente, arquitectura, estructura de archivos y su funcionalidad en una demo.
## ¿Tienes alguna red social donde podamos contactarte?
[Github](https://github.com/thelinch)

## ¿Representas a alguna compañía o empresa?
Kerberos Team

**Comment by jhonfitzgerald** [comment]
Aprovado para este segundo Feves 14/Nov/2019 ^_^
