### ISSUE TITLE
Grado de conocimiento en Integración Continua de los desarrolladores de software en Perú

### ISSUE THREAD

**Issue by MartinPardoGit** [opentech-pe/opentech.pe#29]
## ¿Qué tipo de presentación quieres hacer?
- [x] Lightning Talk (+- 5 minutos)
## ¿Cuál es tu nombre?
John Davis
## Cuéntanos un poco sobre ti
Senior Full Stack Developer
## ¿Cuál es el título de tu charla?
Estadisticas sobre el grado de conocimiento en Integración Continua de los desarrolladores de software en Perú
## Danos una descripción de tu charla (20 palabras)
Grado de “conocimiento” en las 11 prácticas de Integración Continua. 
## ¿Tienes alguna red social donde podamos contactarte?
[facebook](https://www.facebook.com/davis.martinpardo)
## ¿Representas a alguna compañía o empresa?
UNAS

**Comment by jhonfitzgerald** [comment]
Aprovado para este segundo Feves 14/Nov/2019 ^_^

**Comment by jhonfitzgerald** [comment]
Aprovado para este segundo Feves 14/Nov/2019 ^_^
