### ISSUE TITLE
Impacto del Protocolo SSL/TLS hacia los sitios web

### ISSUE THREAD

**Issue by EdgarRueda** [opentech-pe/opentech.pe#37]
> Nuestros eventos se rigen por el siguiente [Código de conducta](/https://github.com/opentech-pe/opentech.pe/blob/master/CODE_OF_CONDUCT.md)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [X] Keynote (30 a 45 minutos)
- [ ] Lightning Talk (+- 5 minutos)

## ¿Cuál es tu nombre?
Edgar Etson Rueda Liberato

## Cuéntanos un poco sobre ti
Ingeniero en Informática y Sistemas, trabaje en la UNAS por dos años como Administrador Web, y realice un trabajo de investigación (tesis) respecto al protocolo SSL/TLS. 

Profesional del sector de la Ingeniería en Informática y Sistemas con gran capacidad de dedicación, orientación a la mejora continua. Durante los últimos 5 años he desempeñado el puesto como Administrador Web, Administrador de base de datos, Instructor de Cursos de la Suite de Microsoft como Word, Excel, PowerPoint, Outlook, Servicios de Office365 en la nube y Operador de Computo en el sector publico.

## ¿Cuál es el título de tu charla?
Impacto del Protocolo SSL/TLS hacia los sitios web,

## Danos una descripción de tu charla (20 palabras)
La charla se enfocara en el uso del protocolo SSL/TLS, si este protocolo genera un impacto positivo o negativo en el rendimiento a sitios web, sabiendo que dicho protocolo asegura la confidencialidad, integridad y autenticación entre el cliente (navegador) y el servidor web. Se vera como el cliente interactua con el servidor para establecer la comunicación cifrada (HTTPS). 

## ¿Tienes alguna red social donde podamos contactarte?
https://www.linkedin.com/in/edgar-rueda/ 
https://twitter.com/EdgarEtson
https://www.facebook.com/eruedal
https://github.com/EdgarRueda

## ¿Representas a alguna compañía o empresa?
No.

## ¿Quieres agregar algo más?
Ninguno, solo proyector.

> Muchas Gracias!
> El equipo de OpenTech

**Comment by jhonfitzgerald** [comment]
TE INVITAMOS ESTE JUEVES 12 DE DICIEMBRE, EN NUESTRO OPENTECH, A REALIZARSE EN LA FACULTAD DE INGENIERIA EN INFORMATICA Y SISTEMAS DE LA UNIVERSIDAD NACIONAL AGRARIA DE LA SELVA.
