### ISSUE TITLE
Share Account: comparte cuentas sin tener que compartir tus credenciales.

### ISSUE THREAD

**Issue by JimmyLoloy1998** [opentech-pe/opentech.pe#38]
> Nuestros eventos se rigen por el siguiente [Código de conducta](/https://github.com/opentech-pe/opentech.pe/blob/master/CODE_OF_CONDUCT.md)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [ ] Keynote (30 a 45 minutos)
- [x] Lightning Talk (+- 5 minutos)

## ¿Cuál es tu nombre?
Loloy Laurencio, Jimmy Erick

## Cuéntanos un poco sobre ti
Estudiante de Informática y Sistemas, muy interesado en la tecnología y las cosas de Hackers y Desarrolladores, me gustaría mucho aprender a hacer Social Enginnering.
Soy un apasionado por la música #DeTodoUnPoco y también baterista... <3  lml

## ¿Cuál es el título de tu charla?
Share Account: comparte cuentas sin tener que compartir tus credenciales.

## Danos una descripción de tu charla (20 palabras)
Share Account y como usarlo para compartir mis cuentas sin necesidad de compartir mi constraseña

## ¿Tienes alguna red social donde podamos contactarte?

[Twitter](https://twitter.com/LoloyJimmy)
[Github](https://github.com/JimmyLoloy1998)
[Facebook](https://www.facebook.com/jimmy.loloy.laurencio.9)

## ¿Quieres agregar algo más?
Solo necesito proyector

> Muchas Gracias!
> El equipo de OpenTech

**Comment by jhonfitzgerald** [comment]
TE INVITAMOS ESTE JUEVES 12 DE DICIEMBRE, EN NUESTRO OPENTECH, A REALIZARSE EN LA FACULTAD DE INGENIERIA EN INFORMATICA Y SISTEMAS DE LA UNIVERSIDAD NACIONAL AGRARIA DE LA SELVA.
