### ISSUE TITLE
Aprendiendo ReactJS o morir en el intento!!

### ISSUE THREAD

**Issue by LuisAngelLucerosaldanaD** [opentech-pe/opentech.pe#39]
> Nuestros eventos se rigen por el siguiente [Código de conducta](/https://github.com/opentech-pe/opentech.pe/blob/master/CODE_OF_CONDUCT.md)
>
> Antes de proponer una charla, recuerda revisarlo para ver si estamos en la
> misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (30 a 45 minutos)
- [ ] Lightning Talk (+- 5 minutos)

## ¿Cuál es tu nombre?
Luis Angel Lucero Saldaña 
## Cuéntanos un poco sobre ti
Hola me llamo ángel 😇, tengo 19 años y soy estudiante de la  carrera de ingeniería en informática y sistemas - UNAS, me especializo en la rama de software, actualmente me estoy enfocando en lo que es el desarrollo de aplicaciones web. 

## ¿Cuál es el título de tu charla?
 

Aprendiendo ReactJS o morir en el intento!!
## Danos una descripción de tu charla (20 palabras)
"Daré a conocer como fue y como es mi experiencia al aprender esta librería de javaScript y lo que me costó dejar el mundo antiguo del desarrollo web"

## ¿Tienes alguna red social donde podamos contactarte?

Facebook : Angel lucero Saldaña 
Github: [AngelDiiA](https://github.com/LuisAngelLucerosaldanaD)
## ¿Representas a alguna compañía o empresa?
No
## ¿Quieres agregar algo más?

No 
> Muchas Gracias!
> El equipo de OpenTech

**Comment by jhonfitzgerald** [comment]
Su charla se pasará para el mes de enero, nos estaremos comunicando con usted.
Muy cordialmente (^_^)

**Comment by jhonfitzgerald** [comment]
Hola Luis Angel, antes que nada queremos agredecerte por esas ganas de querer participar en esta comunidad, te invitamos a que puedas conocer un poco más sobre nosotros visitando nuestra página, y también nuestras redes sociales.
Es un agrado poder contar contigo y con tus conocimientos, recuerda que "la mejor manera de aprender es enseñando".
Respecto a tu charla: Lo estamos pasando para el mes de enero, debido a que ya hemos cubierto la capacidad de tiempo en las charlas de este mes, esperamos tu comprensión y que mantengas esas ganas de querer compartir tus conocimientos.
Atte: Equipo de OpenTech. :heart:
