### ISSUE TITLE
Como sacar provecho de las charlas Open Tech

### ISSUE THREAD

**Issue by tony-ojeda** [opentech-pe/opentech.pe#40]
## ¿Qué tipo de presentación quieres hacer?
- [ ] Keynote (30 a 45 minutos)
- [x] Lightning Talk (+- 5 minutos)

## ¿Cuál es tu nombre?
tony ojeda

## Cuéntanos un poco sobre ti
Soy tony, un chico simple y sencillo que gusta del desarrollo web y compartir conocimiento

## ¿Cuál es el título de tu charla?
"Como sacar provecho de las charlas Open Tech"

## Danos una descripción de tu charla (20 palabras)
Muy pocos conocen lo cuan importante que es asistir a este tipo de eventos y sobre todo lo mucho, mucho, mucho mas importante que es participar en estos. El motivo de este Lightning Talk es un llamado a la reflexión.

> Muchas Gracias!
> El equipo de OpenTech

**Comment by jhonfitzgerald** [comment]
Su charla se pasará para el mes de enero, nos estaremos comunicando con usted.
Muy cordialmente (^_^)

**Comment by jhonfitzgerald** [comment]
Hola Tony, antes que nada queremos agredecerte por esas ganas de querer participar en esta comunidad, te invitamos a que puedas conocer un poco más sobre nosotros visitando nuestra página, y también nuestras redes sociales.
Es un agrado poder contar contigo y con tus conocimientos, recuerda que "la mejor manera de aprender es enseñando".
Respecto a tu charla: Lo estamos pasando para el mes de enero, debido a que ya hemos cubierto la capacidad de tiempo en las charlas de este mes, esperamos tu comprensión y que mantengas esas ganas de querer compartir tus conocimientos.
Atte: Equipo de OpenTech. :heart:
