### ISSUE TITLE
`Previous events` page doesn't exist

### ISSUE THREAD

**Issue by KattyaCuevas** [opentech-pe/opentech.pe#75]
**Describe the bug**
In the NavBar of the main page, the link to the previous event returns a 404 status code.

**To Reproduce**
1. Go to `https://www.opentech.pe/`
2. Click on `Eventos anteriores` in the NavBar.
3. See 404 page

**Expected behavior**
See the list of previous events.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - macOS Catalina, v 10.15.7 
 - Brave (chromium) v 1.11.104

**Smartphone (please complete the following information):**
None

**Additional context**
None

**Comment by paulotijero** [comment]
It happens that in the migration to NextJS that view was not built, you can take a look at how it would look in figma => [link](https://www.figma.com/file/ND9lxnSh7DA4mGFIfFodhkap/OT-Page?node-id=134%3A2)
