### ISSUE TITLE
Unnecessary link.

### ISSUE THREAD

**Issue by JimmyLoloy98** [opentech-pe/opentech.pe#89]
**To Reproduce**
1. Go to 'previous events' view.
2. Click on https://www.opentech.pe/previous-events in header.
3. Unnecessary link.

**Expected behavior**
NO link in header.

**Screenshots**
![image](https://user-images.githubusercontent.com/49881423/112398817-f1a3d980-8cd2-11eb-8635-3aafab568c74.png)

**Comment by paulotijero** [comment]
No logro entender cual es el error, podrías describirlo un poco más porfavor.

**Comment by JimmyLoloy98** [comment]
Dentro de la vista "Eventos anteriores", nuevamente se encuentra en el Header, el link a "Eventos anteriores".
